import type { Dish } from "@/types/experienciaVR";

export const DISHES: Dish[] = [
  {
    id: "acevichado",
    nombre: "Acevichado",
    categoria: "Acevichados",
    kanji: "酢",
    ingredientes: "Ebi furai y palta cub, con atún y salsa acevichada",
    img: "/images/menu/acevichado.webp",
    riceColor: 0xf5f1e6,
    fillingColor: 0x7a9b52,
    topping: { style: "drape", color: 0xc96b5a },
    drizzle: { style: "zigzag", color: 0xf2e6c9 },
    garnish: [{ type: "chili", color: 0xcc4433, count: 5 }],
  },
  {
    id: "anticuchero-roll",
    nombre: "Anticuchero Roll",
    categoria: "Nikkei Fusion",
    kanji: "融",
    ingredientes: "Palta sakana furai cub de pulpo, atún flameado y salsa anticuchero",
    img: "/images/menu/anticuchero-roll.webp",
    riceColor: 0xf5f1e6,
    fillingColor: 0x6b8e4e,
    topping: { style: "drape", color: 0x7a2f22 },
    drizzle: { style: "zigzag", color: 0x7a2f1c },
    garnish: [{ type: "sesame", color: 0x161616, count: 6 }],
  },
  {
    id: "brasa-roll",
    nombre: "Brasa Roll",
    categoria: "Nikkei Fusion",
    kanji: "融",
    ingredientes: "Pollo furai y palta cub, en salsa de ají amarillo y papas crocantes",
    img: "/images/menu/brasa-roll.webp",
    riceColor: 0xf5f1e6,
    fillingColor: 0xf2ece0,
    topping: { style: "crispy", color: 0xd9a441 },
    drizzle: { style: "zigzag", color: 0xd98a9a },
    garnish: [{ type: "herb", color: 0x4a6b3a, count: 4 }],
  },
  {
    id: "furai-roll",
    nombre: "Furai Roll",
    categoria: "Salmón & Atún",
    kanji: "鮭",
    ingredientes: "Maki frito de salmón, queso crema y palta",
    img: "/images/menu/furai-roll.webp",
    riceColor: 0xd9a441,
    fillingColor: 0xf2ece0,
    fillingColor2: 0xe8875b,
    topping: null,
    drizzle: null,
    garnish: [],
  },
  {
    id: "gaucho",
    nombre: "Gaucho",
    categoria: "Nikkei Fusion",
    kanji: "融",
    ingredientes: "Lomo tempura, queso crema cub, chimichurri de lomo flameado",
    img: "/images/menu/gaucho.webp",
    riceColor: 0xf5f1e6,
    fillingColor: 0xf2ece0,
    topping: { style: "drape", color: 0x6b3a2a },
    drizzle: null,
    garnish: [{ type: "herb", color: 0x4a6b2f, count: 8 }],
  },
  {
    id: "huancaina-roll",
    nombre: "Huancaína Roll",
    categoria: "Nikkei Fusion",
    kanji: "融",
    ingredientes: "Sakana furai y palta cub en salsa huancaína",
    img: "/images/menu/huancaina-roll.webp",
    riceColor: 0xf5f1e6,
    fillingColor: 0x7a9b52,
    fillingColor2: 0xe0a08c,
    topping: { style: "sauceCap", color: 0xe8d27a },
    drizzle: null,
    garnish: [
      { type: "chili", color: 0xcc4433, count: 3 },
      { type: "herb", color: 0x4a6b2f, count: 3 },
    ],
  },
  {
    id: "leche-de-tigre",
    nombre: "Leche de Tigre",
    categoria: "Nikkei Fusion",
    kanji: "融",
    ingredientes: "Ebi furai y palta cub, con pescado blanco y leche de tigre",
    img: "/images/menu/leche-de-tigre.webp",
    riceColor: 0xf5f1e6,
    fillingColor: 0x7a9b52,
    fillingColor2: 0xe0a08c,
    topping: { style: "sauceCap", color: 0xe8d27a },
    drizzle: null,
    garnish: [{ type: "sesame", color: 0x111111, count: 7 }],
  },
  {
    id: "seiji",
    nombre: "Seiji Roll",
    categoria: "Especiales",
    kanji: "特",
    ingredientes:
      "Palta sakana furai arrebozado frito cub, salsa seiji a base de trucha ahumada, piel de salmón crocante y tare",
    img: "/images/menu/seiji.webp",
    riceColor: 0xd9a441,
    fillingColor: 0xf2ece0,
    fillingColor2: 0xe8875b,
    topping: null,
    drizzle: null,
    garnish: [],
  },
  {
    id: "tiradito-roll",
    nombre: "Tiradito Roll",
    categoria: "Nikkei Fusion",
    kanji: "融",
    ingredientes: "Sakana furai y palta cub, con pescado blanco y tiradito de ají amarillo",
    img: "/images/menu/tiradito-roll.webp",
    riceColor: 0xf5f1e6,
    fillingColor: 0x7a9b52,
    topping: { style: "drape", color: 0xb3792e },
    drizzle: { style: "zigzag", color: 0x3a2412 },
    garnish: [{ type: "herb", color: 0x4a6b2f, count: 4 }],
  },
];
